region                    = "us-east-1"
vpc_name                  = "eks-vpc"
vpc_cidr                  = "10.0.0.0/16"
az1                       = "us-east-1a"
az2                       = "us-east-1b"

public_subnet_az1_cidr    = "10.0.1.0/24"
public_subnet_az2_cidr    = "10.0.2.0/24"
private_subnet_az1_cidr   = "10.0.3.0/24"
private_subnet_az2_cidr   = "10.0.4.0/24"

iam_role_name             = "eks-iam-role"
eks_cluster_name          = "eks-cluster"
fargate_profile_name      = "eks-fargate-profile"
eks_namespace             = "eks-ns"
