name: EKS Fargate Apply/Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      cluster_name:
        description: 'EKS Cluster Name (created from Terraform)'
        required: true
        default: 'my-eks-cluster'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 557548602903

jobs:
  eks-deployment:
    name: EKS Fargate Deployment
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::557548602903:role/mytestrole-OIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name ${{ github.event.inputs.cluster_name }}

      - name: Deploy or Destroy Kubernetes Resources
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            echo "🚀 Applying Kubernetes manifests..."
            kubectl apply -f app/k8s/deployment-appointment.yaml
            kubectl apply -f app/k8s/service-appointment.yaml
            kubectl apply -f app/k8s/deployment-patient.yaml
            kubectl apply -f app/k8s/service-patient.yaml
            kubectl apply -f app/k8s/ingress.yaml
            echo "✅ Apply completed!"
          elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            echo "🔥 Destroying Kubernetes resources..."
            kubectl delete -f app/k8s/ingress.yaml --ignore-not-found
            kubectl delete -f app/k8s/service-patient.yaml --ignore-not-found
            kubectl delete -f app/k8s/deployment-patient.yaml --ignore-not-found
            kubectl delete -f app/k8s/service-appointment.yaml --ignore-not-found
            kubectl delete -f app/k8s/deployment-appointment.yaml --ignore-not-found
            echo "🗑️ Destroy completed."
          else
            echo "❌ Invalid mode selected."
            exit 1
          fi
