name: EKS Fargate Apply/Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform (apply or destroy)'
        required: true
        default: 'apply'
      cluster_name:
        description: 'EKS Cluster Name (created from Terraform)'
        required: true
        default: 'eks-cluster'

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Install kubectl
        run: |
          # Fetch the stable Kubernetes version
          KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt | tr -d '\n')

          # Download the kubectl binary for the stable version
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"

          # Install kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS Cluster
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy or Destroy Kubernetes Resources
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            echo "🚀 Applying Kubernetes manifests..."
            kubectl apply -f app/appointment-service/appointment-deployment.yaml || true
            kubectl apply -f app/appointment-service/appointment-service.yaml || true
            kubectl apply -f app/patient-service/patient-deployment.yaml || true
            kubectl apply -f app/patient-service/patient-service.yaml || true
            kubectl apply -f app/nginx-ingress.yaml || true
            echo "✅ Apply completed!"
          elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            echo "🔥 Destroying Kubernetes resources..."
            kubectl delete -f app/nginx-ingress.yaml --ignore-not-found
            kubectl delete -f app/patient-service/patient-service.yaml --ignore-not-found
            kubectl delete -f app/patient-service/patient-deployment.yaml --ignore-not-found
            kubectl delete -f app/appointment-service/appointment-service.yaml --ignore-not-found
            kubectl delete -f app/appointment-service/appointment-deployment.yaml --ignore-not-found
            echo "🗑️ Destroy completed."
          else
            echo "❌ Invalid action selected!"
            exit 1
          fi
